{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
    "docker"
  ],
  "install": [
    "travis_wait 30 mvn install"
  ],
  "before_install": [
    "docker build -t coolshaddy/docker-react -f Dockerfile.dev ."
  ],
  "script": [
    "docker run coolshaddy/docker-react npm run test -- --coverage"
  ]
}