sudo: required
services:
 - docker

before_install:
 - docker build -t coolshaddy/docker-react -f Dockerfile.dev .

script:
 - docker run coolshaddy/docker-react npm run test -- --coverage --watchAll=false
